### ISSUE TITLE
indexdRPCError since recent update

### ISSUE THREAD

**Issue by 3kynox** [CounterpartyXCP/indexd-server#12]
Hello,

since a recent update, we got an indexdRPCError and our blockchain server do not work anymore, details:

```
[2018-09-20 08:49:08][ERROR] API Exception: {'args': ('Cannot communicate with mainnet indexd server at `http://localhost:8432/a/***concerned_wallet***/utxos`.',), 'message': 'Cannot communicate with mainnet indexd server at` http://localhost:8432/a/***concerned_wallet***/utxos`.', 'type': 'IndexdRPCError'}

counterparty_1           | Traceback (most recent call last):
counterparty_1           |   File "/usr/local/lib/python3.5/dist-packages/jsonrpc/manager.py", line 108, in _get_responses
counterparty_1           |     result = method(*request.args, **request.kwargs)
counterparty_1           |   File "/counterparty-lib/counterpartylib/lib/api.py", line 509, in create_method
counterparty_1           |     return compose_transaction(self.db, name=tx, params=transaction_args, **common_args)
counterparty_1           |   File "/counterparty-lib/counterpartylib/lib/api.py", line 374, in compose_transaction
counterparty_1           |     extended_tx_info=extended_tx_info)
counterparty_1           |   File "/counterparty-lib/counterpartylib/lib/transaction.py", line 461, in construct
counterparty_1           |     unspent = backend.get_unspent_txouts(source, unconfirmed=allow_unconfirmed_inputs)
counterparty_1           |   File "/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 158, in get_unspent_txouts
counterparty_1           |     unspent = BACKEND().get_unspent_txouts(source)
counterparty_1           |   File "/counterparty-lib/counterpartylib/lib/backend/indexd.py", line 258, in get_unspent_txouts
counterparty_1           |     return indexd_rpc_call('/a/'+source+'/utxos')
counterparty_1           |   File "/counterparty-lib/counterpartylib/lib/backend/indexd.py", line 296, in indexd_rpc_call
counterparty_1           |     raise IndexdRPCError('Cannot communicate with {} indexd server at `{}`.'.format(network, util.clean_url_for_log(url)))
counterparty_1           | counterpartylib.lib.backend.indexd.IndexdRPCError: Cannot communicate with mainnet indexd server at `http://localhost:8432/a/***concerned_wallet***/utxos`.
```

Could someone have direction to sort out this problem please?

Thanks

**Comment by chiguireitor** [comment]
ACK, need to fix support for the develop branch of fednode

**Comment by chiguireitor** [comment]
Is this still happening on the develop branch?

**Comment by chiguireitor** [comment]
fednode uninstall and then fednode install should solve it, also, be sure to check the bitcoin/bitcoin.conf, counterparty/server.conf and indexd/index.env to be correctly configured as per the .default suffixed files

**Comment by longhoangwkm** [comment]
i notice that indexd-server only index for new block. For existing blocks are generated meanwhile indexd got crash is not

**Comment by chiguireitor** [comment]
No resync mechanism atm, should have one tbh, i'll see what can i include there

**Comment by chiguireitor** [comment]
Pushed a change to master, if you can run indexd with parameters `--resync BLOCKHASH` with BLOCKHASH being the block where the sync failed, let me know if it works plz.

**Comment by longhoangwkm** [comment]
Hey John @chiguireitor, It has resync mechanism. I checked. It inside https://github.com/CounterpartyXCP/indexd/blob/master/resync.js.

```
Mon, 20 Jan 2020 09:44:18 GMT indexd Connecting 00000000e6d7b568a7957227abd3906cc6cfba9fb90abcb870527e6e05ca492a @ 11625
Mon, 20 Jan 2020 09:44:18 GMT indexd Connected 00000000e6d7b568a7957227abd3906cc6cfba9fb90abcb870527e6e05ca492a @ 11625
Mon, 20 Jan 2020 09:44:18 GMT indexd Downloading 000000007a8a21eb7a5d58946dfe4686827bde2d5b270c3ebc611301c92c34f1 (for script,tx,txin,txo)
Mon, 20 Jan 2020 09:44:18 GMT indexd:rpc getblock [ '000000007a8a21eb7a5d58946dfe4686827bde2d5b270c3ebc611301c92c34f1',
  2 ]
Mon, 20 Jan 2020 09:44:18 GMT indexd Connecting 000000007a8a21eb7a5d58946dfe4686827bde2d5b270c3ebc611301c92c34f1 @ 11626
Mon, 20 Jan 2020 09:44:18 GMT indexd Connected 000000007a8a21eb7a5d58946dfe4686827bde2d5b270c3ebc611301c92c34f1 @ 11626
Mon, 20 Jan 2020 09:44:18 GMT indexd Downloading 00000000451e17c403032b5e9124a1aa25eabbed7ca0efc6e17f115bb030e04a (for script,tx,txin,txo)
Mon, 20 Jan 2020 09:44:18 GMT indexd:rpc getblock [ '00000000451e17c403032b5e9124a1aa25eabbed7ca0efc6e17f115bb030e04a',
  2 ]
Mon, 20 Jan 2020 09:44:18 GMT indexd Connecting 00000000451e17c403032b5e9124a1aa25eabbed7ca0efc6e17f115bb030e04a @ 11627
Mon, 20 Jan 2020 09:44:18 GMT indexd Connected 00000000451e17c403032b5e9124a1aa25eabbed7ca0efc6e17f115bb030e04a @ 11627
Mon, 20 Jan 2020 09:44:18 GMT indexd Downloading 000000004e2895151bfb4aec11f13394c210c4a5383a1fb952dcb23ccfa7e6d5 (for script,tx,txin,txo)
Mon, 20 Jan 2020 09:44:18 GMT indexd:rpc getblock [ '000000004e2895151bfb4aec11f13394c210c4a5383a1fb952dcb23ccfa7e6d5',
  2 ]
Mon, 20 Jan 2020 09:44:18 GMT indexd Connecting 000000004e2895151bfb4aec11f13394c210c4a5383a1fb952dcb23ccfa7e6d5 @ 11628
Mon, 20 Jan 2020 09:44:18 GMT indexd Connected 000000004e2895151bfb4aec11f13394c210c4a5383a1fb952dcb23ccfa7e6d5 @ 11628
Mon, 20 Jan 2020 09:44:18 GMT indexd Downloading 000000008d207587616baeb0017cc207cca752d9a753958828b3199f4283be36 (for script,tx,txin,txo)
Mon, 20 Jan 2020 09:44:18 GMT indexd:rpc getblock [ '000000008d207587616baeb0017cc207cca752d9a753958828b3199f4283be36',
  2 ]
Mon, 20 Jan 2020 09:44:18 GMT indexd Connecting 000000008d207587616baeb0017cc207cca752d9a753958828b3199f4283be36 @ 11629
Mon, 20 Jan 2020 09:44:18 GMT indexd Connected 000000008d207587616baeb0017cc207cca752d9a753958828b3199f4283be36 @ 11629
Mon, 20 Jan 2020 09:44:18 GMT indexd Downloading 00000000053a31f4de0ad70e58f12a657ca3e2826aba709cba4a06120d45662e (for script,tx,txin,txo)
Mon, 20 Jan 2020 09:44:18 GMT indexd:rpc getblock [ '00000000053a31f4de0ad70e58f12a657ca3e2826aba709cba4a06120d45662e',
  2 ]
Mon, 20 Jan 2020 09:44:18 GMT indexd Connecting 00000000053a31f4de0ad70e58f12a657ca3e2826aba709cba4a06120d45662e @ 11630
Mon, 20 Jan 2020 09:44:18 GMT indexd Connected 00000000053a31f4de0ad70e58f12a657ca3e2826aba709cba4a06120d45662e @ 11630
Mon, 20 Jan 2020 09:44:18 GMT indexd Downloading 00000000c54872986bd064d8e81dea6cde913d240c9265274e663855eda5dd52 (for script,tx,txin,txo)
Mon, 20 Jan 2020 09:44:18 GMT indexd:rpc getblock [ '00000000c54872986bd064d8e81dea6cde913d240c9265274e663855eda5dd52',
  2 ]
Mon, 20 Jan 2020 09:44:18 GMT indexd Connecting 00000000c54872986bd064d8e81dea6cde913d240c9265274e663855eda5dd52 @ 11631
Mon, 20 Jan 2020 09:44:18 GMT indexd Connected 00000000c54872986bd064d8e81dea6cde913d240c9265274e663855eda5dd52 @ 11631
Mon, 20 Jan 2020 09:44:18 GMT indexd Downloading 00000000c060828dfeeab4a34087331535d416495bf4ba050fa77d8212dd1f78 (for script,txin,tx,txo)
Mon, 20 Jan 2020 09:44:18 GMT indexd:rpc getblock [ '00000000c060828dfeeab4a34087331535d416495bf4ba050fa77d8212dd1f78',
  2 ]
Mon, 20 Jan 2020 09:44:18 GMT indexd Connecting 00000000c060828dfeeab4a34087331535d416495bf4ba050fa77d8212dd1f78 @ 11632
```

**Comment by longhoangwkm** [comment]
I turn on indexd:rpc log and found problem come from `getblock` RPC. I used too old bitcoind ver 0.13.0. With getblock argument is true and false instead 0/1/2 value. Newer version use 0/1/2. This problem causes resync failure and an to occur error `Cannot communicate with mainnet indexd server at `http://localhost:8432/a/***concerned_wallet***/utxos`.',), 'message': 'Cannot communicate with mainnet indexd server at` http://localhost:8432/a/***concerned_wallet***/utxos`

**Comment by chiguireitor** [comment]
Gotcha, interesting that the bitcoin version affects this functionality.
