### ISSUE TITLE
Version of npm/node

### ISSUE THREAD

**Issue by weex** [CounterpartyXCP/indexd-server#25]
I tried installing this with the latest npm/node on my debian server but get an error. Any idea which version of node is preferred?

```
$ node --version
v12.13.0
$ npm --version
6.13.0
$ npm install
...snip...
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/home/user/.nvm/versions/node/v12.13.0/bin/node" "/home/user/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/code/indexd-server/node_modules/leveldown
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN counterparty-indexd-server@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@4.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-11-17T02_11_40_417Z-debug.log
```

**Comment by chiguireitor** [comment]
Currently indexd-server is only compatible with node-carbon (as it is run from the dockerfile).

Updating to a newer library version of indexd should be enough, but unfortunately there's breaking compatibility changes upstream, so this will not be possible atm.
