### ISSUE TITLE
 TypeError: Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by mandelmonkey** [CounterpartyXCP/indexd-server#6]
I followed the install instructions using the latest bitcoincore and the indexd branches of counterpartylib and cli

npm:v5.5.1
node:v9.2.0

I start the server as follows

```
forge@dev-test-xcpd-2:~/indexd-server$ forever index.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Wed, 15 Nov 2017 15:31:43 GMT index Initializing blockchain connection (for testnet)
Wed, 15 Nov 2017 15:31:43 GMT index starting API server
Wed, 15 Nov 2017 15:31:43 GMT index App listening on port 18432
```

then I call 
curl http://127.0.0.1:18432/status

and the following error is thrown

```
Wed, 15 Nov 2017 15:31:47 GMT express ERR: /status TypeError: Cannot read property 'height' of undefined
    at parallel (/home/forge/indexd-server/lib/express.js:60:42)
    at end (/home/forge/indexd-server/node_modules/run-parallel/index.js:16:15)
    at done (/home/forge/indexd-server/node_modules/run-parallel/index.js:20:10)
    at each (/home/forge/indexd-server/node_modules/run-parallel/index.js:26:7)
    at /home/forge/indexd-server/node_modules/run-parallel/index.js:36:43
    at batch.forEach (/home/forge/indexd-server/node_modules/yajrpc/index.js:72:7)
    at Array.forEach (<anonymous>)
    at dhttp (/home/forge/indexd-server/node_modules/yajrpc/index.js:61:11)
    at done (/home/forge/indexd-server/node_modules/dhttp/index.js:17:19)
    at handle (/home/forge/indexd-server/node_modules/dhttp/index.js:61:7)

/home/forge/indexd-server/lib/express.js:89
      let tipHeight = results.tip.height
```

**Comment by deweller** [comment]
This is a bug when bitcoind is not available.

Looks like it was not able to establish a connection to bitcoind.  Do your `.env` settings check out?

```
RPC=???
RPCPASSWORD=???
RPCUSER=???
```

**Comment by mandelmonkey** [comment]
I think so do these look ok to you? 

.env
```
DEBUG=index,zmq,zmq:block,express
INDEXDB=/data/indexd/indexd-testnet
RPC=http://localhost:18332
RPCPASSWORD={PASSWORD}
RPCUSER=btcd-rpc
ZMQ=tcp://localhost:28332
TESTNET=true
SERVER_PORT=18432
NODE_ENV=production
RPCBATCHSIZE=500
RPCCONCURRENT=32
```

.bitcoin.conf
```
rpcuser=btcd-rpc
rpcpassword={PASSWORD}
rpcconnect=localhost
rpcallowip=0.0.0.0/0
rpcthreads=1000
rpctimeout=300
server=1
daemon=1
txindex=1
addrindex=1
rpcport=18332
testnet=3
zmqpubhashblock=tcp://127.0.0.1:28332
zmqpubhashtx=tcp://127.0.0.1:28332
rpcserialversion=0
```

**Comment by deweller** [comment]
That mismatch between `localhost` and `127.0.0.1` for the ZMQ settings might be significant.

**Comment by deweller** [comment]
My best guess is that the indexd server is not able to connect to the bitcoind RPC server.  But I can't tell for sure from the logs.

**Comment by mandelmonkey** [comment]
thanks restarting bitcoind seemed to make it work

**Comment by deweller** [comment]
Keeping this open because it should not crash when bitcoin is unavailable

**Comment by mandelmonkey** [comment]
fair point ;-)
